etcd:
  name: "{HOSTNAME}"
  advertise_client_urls: "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  listen_client_urls: "http://0.0.0.0:2379"
  listen_peer_urls: "http://{PRIVATE_IPV4}:2380"
  initial_cluster: "{HOSTNAME}=http://{PRIVATE_IPV4}:2380"

passwd:
  users:
    - name: coreos
      sshAuthorizedKeys:
        - "${ssh_authorized_keys}"
      uid: 1000

storage:
  files:
    - path: /etc/hostname
      filesystem: root
      contents:
        inline: |
          rancher-server

systemd:
  units:
    - name: rancher-server.service
      enabled: true
      contents: |
        [Unit]
        Description=Rancher Server
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutSec=600
        Type=oneshot
        ExecStartPre=/usr/bin/docker pull rancher/server:v1.6.25
        ExecStart=/usr/bin/docker run \
          --name rancher \
          --hostname rancher \
          --rm \
          -p 80:8080 \
          -p 9345:9345 \
          rancher/server:v1.6.25 \
          --db-host "${rancher_db_host}" \
          --db-name "${rancher_db_name}" \
          --db-pass "${rancher_db_pass}" \
          --db-user "${rancher_db_user}" \
        ;

        [Install]
        WantedBy=multi-user.target

    - name: getty@.service
      dropins:
        - name: no-disallocate.conf
          contents: |
            [Service]
            TTYVTDisallocate=no
