systemd:
  units:
    - name: rancher-bootstrap.service
      enabled: true
      contents: |
        [Unit]
        Description=Rancher member
        After=docker.service
        Requires=docker.service

        [Service]
        ExecStart=${startup}
        Type=oneshot

        [Install]
        WantedBy=multi-user.target

    - name: getty@.service
      dropins:
        - name: no-disallocate.conf
          contents: |
            [Service]
            TTYVTDisallocate=no
